name: Build and push

on:
  push:
    branches: [ main ]

env:
  REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
  REGISTRY_IMAGE: ${{ secrets.REGISTRY_IMAGE }}
  DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}

jobs:
  build:
    name: "Checkout and build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Build image"
        run: docker build . --tag ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_IMAGE }}:latest

      - name: "Login to Registry"
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: "Publish image"
        run: docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_IMAGE }}:latest